### PR TITLE
GH-556: Fix spelling errors flagged by aspell

### PR DESCRIPTION
**Pull request by ybyzek**
Addresses https://github.com/confluentinc/kafka-tutorials/issues/556

Spelling corrected in adoc files only

### CODE REVIEW

**Comment by ybyzek** [comment]
Note: there is one build failure in the second block of tests, but this PR modifies only `adoc` files and the tutorial that failed (`connect-add-key-to-source`) was not even touched by this PR.

**Comment by gAmUssA** [comment]
is there a way to run this `aspell` during build/PR? that would be helpful

**Review by bbejeck — APPROVED** [review]
Thanks for the PR @ybyzek LGTM

**Comment by bbejeck** [comment]
>is there a way to run this aspell during build/PR? that would be helpful

@gAmUssA I agree, see https://github.com/confluentinc/kafka-tutorials/issues/596

**Pull request merged**
