### PR TITLE
Updated header navigation to match developer.confluent.io

### PR DESCRIPTION
**Pull request by iPzard**
### Description
Updated header navigation (except logos) to match [developer.confluent.io](https://developer.confluent.io/)

### Staging Docs

http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/updated-header-navigation-section/

### CODE REVIEW

**Comment by rmoff** [comment]
LGTM. Ping @ybyzek for second review.

**Review by rmoff — APPROVED** [review]
LGTM, subject to @ybyzek being +1

**Comment by ybyzek** [comment]
@iPzard is it expected that http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/updated-header-navigation-section/ nav bar font looks different from https://developer.confluent.io?

**Comment by hartantothio** [comment]
Issue observed here -- http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/updated-header-navigation-section/kafka-console-consumer-producer-basics/confluent.html

**Comment by hartantothio** [comment]
Also, why is the url starts with `/updated-header-navigation-section`?

**Comment by iPzard** [comment]
> @iPzard is it expected that http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/updated-header-navigation-section/ nav bar font looks different from https://developer.confluent.io?

Updated in https://github.com/confluentinc/kafka-tutorials/pull/995/commits/63e87729abed4ffb9898ff692fed090e6fc63355

**Comment by iPzard** [comment]
> Issue observed with the hero here -- http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/updated-header-navigation-section/kafka-console-consumer-producer-basics/confluent.html

Great catch, updated in https://github.com/confluentinc/kafka-tutorials/pull/995/commits/2b04391905a81b5aa9a8ce3d801d7f3ae0dcf613 to resolve this. 

For the URL path question, it's because that's the branch name.. http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/{branch-name}/

**Comment by iPzard** [comment]
> @iPzard http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/updated-header-navigation-section/ still looks different from https://developer.confluent.io in the latest build. Are you seeing the difference as well?

Added the required fonts and letter spacing settings from developer.confluent.io to get the text to match exactly, also updated scroll behavior and styles to match in https://github.com/confluentinc/kafka-tutorials/pull/995/commits/103b0a27ec6324326ffdd6244b7d71f2e134c0f3

**Review by ybyzek — APPROVED** [review]
LGTM thanks @iPzard

**Comment by hartantothio** [comment]
The quickstart button in navigation leads to 404.

Other than that, looks good.

**Comment by iPzard** [comment]
> The quickstart button in navigation leads to 404.
> 
> Other than that, looks good.

Good catch! Updated in https://github.com/confluentinc/kafka-tutorials/pull/995/commits/4956c6acfaaf7d10ff5380c454881ca246c8118b

**Pull request merged**
