### PR TITLE
Update all version to latest CP 7.1.0 and AK 3.1.0 code

### PR DESCRIPTION
**Pull request by daveklein**
### Description

Project-wide update of versioned references of the following CP components to version 7.1.0:
- cp-zookeeper
- cp-kafka
- cp-schema-registry
- cp-enterprise-control-center
- cp-server
- cp-server-connect-base
- cp-ksqldb-server
- cp-server-kafka-base
Previous versions were either 6.1.0, 6.1.1, 6.2.1, 7.0.0, or 7.0.1

### CODE REVIEW

**Review by ybyzek — CHANGES_REQUESTED** [review]
Thanks for the PR @daveklein .  Can you also update the versions in the various `build.gradle` files?

**Comment by daveklein** [comment]
@ybyzek The only `build.gradle` components that had a version number that corresponded to our cp versions was `kafka-streams-avro-serde:6.2.1` and `com.github.jengelman.gradle.plugins:shadow:6.1.0`. I didn't think the shadow jar plugin was part of CP, and when I tried changing the `kafka-streams-avro-serde` to `7.1.0`, the tutorial I was testing with failed to build. When I updated the cp components but left that item in `build.gradle`, it worked.  I guess I will try to figure out what is breaking with `kafka-streams-avro-serde:7.1.0`.  I'll dig into this, but please shout out if any of this raises any red flags to you. Thanks!

**Comment by ybyzek** [comment]
@daveklein looks like it's still not compiling, see Semaphore stage `Build and Test Java (Kafka and Kafka Streams) Only`

**Comment by ybyzek** [comment]
@daveklein the latest error is due https://issues.apache.org/jira/browse/KAFKA-9559 and can be fixed by:

```
diff --git a/_includes/tutorials/merging/kstreams/code/src/test/java/io/confluent/developer/MergeStreamsTest.java b/_includes/tutorials/merging/kstreams/code/src/test/java/io/confluent/developer/MergeStreamsTest.java
index 59d19a0ee..12088729c 100644
--- a/_includes/tutorials/merging/kstreams/code/src/test/java/io/confluent/developer/MergeStreamsTest.java
+++ b/_includes/tutorials/merging/kstreams/code/src/test/java/io/confluent/developer/MergeStreamsTest.java
@@ -6,6 +6,7 @@ import org.apache.kafka.common.serialization.Serializer;
 import org.apache.kafka.streams.TestInputTopic;
 import org.apache.kafka.streams.Topology;
 import org.apache.kafka.streams.TopologyTestDriver;
+import org.apache.kafka.streams.StreamsConfig;
 import org.junit.After;
 import org.junit.Assert;
 import org.junit.Test;
@@ -51,6 +52,8 @@ public class MergeStreamsTest {
     public void testMergeStreams() throws IOException {
         MergeStreams ms = new MergeStreams();
         Properties allProps = ms.loadEnvProperties(TEST_CONFIG_FILE);
+        allProps.put(StreamsConfig.DEFAULT_KEY_SERDE_CLASS_CONFIG, Serdes.String().getClass().getName());
+        allProps.put(StreamsConfig.DEFAULT_VALUE_SERDE_CLASS_CONFIG, Serdes.String().getClass().getName());
 
         String rockTopic = allProps.getProperty("input.rock.topic.name");
         String classicalTopic = allProps.getProperty("input.classical.topic.name");
```

**Comment by ybyzek** [comment]
@krisajenkins unfortunately there are more.  To run locally and ensure a clean compile:

```
./gradlew clean test
```

**Comment by ybyzek** [comment]
Updates include:

* CP packages to 7.1.0
* AK packages to 3.1.0
* Gradle?

**Comment by ybyzek** [comment]
@bbejeck I've addressed several errors but this one I'm stuck on: https://confluentinc.semaphoreci.com/jobs/2ff6e315-ed0f-4714-b907-1e21a63d1d43 .  Do you have any idea on what's happening and how to resolve it?

**Comment by ybyzek** [comment]
> @bbejeck I've addressed several errors but this one I'm stuck on: https://confluentinc.semaphoreci.com/jobs/2ff6e315-ed0f-4714-b907-1e21a63d1d43 . Do you have any idea on how to resolve it? I've reverted the versions in the `build.gradle` file (and restored the deprecated command in the code) and it passes, so it's something to do with the change.
> 
> Update: some records are skipped -- they are old, static timestamps?
> 
> ```
>     [Test worker] WARN org.apache.kafka.streams.kstream.internals.KStreamWindowAggregate - Skipping record for expired window. topic=[tumbling-window-app-KSTREAM-AGGREGATE-STATE-STORE-0000000002-repartition] partition=[0] offset=[4] timestamp=[1556197200000] window=[1556197200000,1556197800000) expiration=[1556226660000] streamTime=[1556226660000]
>     [Test worker] WARN org.apache.kafka.streams.kstream.internals.KStreamWindowAggregate - Skipping record for expired window. topic=[tumbling-window-app-KSTREAM-AGGREGATE-STATE-STORE-0000000002-repartition] partition=[0] offset=[5] timestamp=[1556197260000] window=[1556197200000,1556197800000) expiration=[1556226660000] streamTime=[1556226660000]
>     [Test worker] WARN org.apache.kafka.streams.kstream.internals.KStreamWindowAggregate - Skipping record for expired window. topic=[tumbling-window-app-KSTREAM-AGGREGATE-STATE-STORE-0000000002-repartition] partition=[0] offset=[6] timestamp=[1556220600000] window=[1556220600000,1556221200000) expiration=[1556226660000] streamTime=[1556226660000]
>     [Test worker] WARN org.apache.kafka.streams.kstream.internals.KStreamWindowAggregate - Skipping record for expired window. topic=[tumbling-window-app-KSTREAM-AGGREGATE-STATE-STORE-0000000002-repartition] partition=[0] offset=[7] timestamp=[1556220900000] window=[1556220600000,1556221200000) expiration=[1556226660000] streamTime=[1556226660000]
>     [Test worker] WARN org.apache.kafka.streams.kstream.internals.KStreamWindowAggregate - Skipping record for expired window. topic=[tumbling-window-app-KSTREAM-AGGREGATE-STATE-STORE-0000000002-repartition] partition=[0] offset=[8] timestamp=[1556190900000] window=[1556190600000,1556191200000) expiration=[1556226660000] streamTime=[1556226660000]
>     [Test worker] WARN org.apache.kafka.streams.kstream.internals.KStreamWindowAggregate - Skipping record for expired window. topic=[tumbling-window-app-KSTREAM-AGGREGATE-STATE-STORE-0000000002-repartition] partition=[0] offset=[9] timestamp=[1556192400000] window=[1556192400000,1556193000000) expiration=[1556226660000] streamTime=[1556226660000]
> ```

@bbejeck I got the test case for `tumbling-windows` to pass but it necessitated reordering the records according to timestamp.  I had read somewhere that KS assumes some ordering, which gave me the clue, but then I don't understand why this test case ever passed.  Can you please look at the changes and let me know what you think?  https://github.com/confluentinc/kafka-tutorials/pull/1229/files?file-filters%5B%5D=.bat&file-filters%5B%5D=.gradle&file-filters%5B%5D=.jar&file-filters%5B%5D=.java&file-filters%5B%5D=.md&file-filters%5B%5D=.properties&file-filters%5B%5D=.scala&file-filters%5B%5D=.yml&file-filters%5B%5D=No+extension&show-viewed-files=true

**Review by bbejeck — APPROVED** [review]
LGTM pending tests passing

**Comment by ybyzek** [comment]
@bbejeck I'd appreciate your assistance on one more failing KT for https://developer.confluent.io/tutorials/error-handling/kstreams.html which when I run locally, it returns only the first record `ALL` and then appears to shut down and doesn't return the remaining ones.

**Comment by ybyzek** [comment]
To filter the file changes outside of the version revs in `docker-compose.yml` and `build.gradle`, checkout the branch and run:

```
git diff master --name-only | grep -v docker-compose.yml | grep -v build.gradle
```

**Comment by ybyzek** [comment]
Some KTs were not updated and require further investigation: https://github.com/confluentinc/kafka-tutorials/issues/1256

**Pull request merged**
