### PR TITLE
Additional updates for prototype

### PR DESCRIPTION
**Pull request by scott-confluent**
### Description

- Add color palette
- Add button mixin
- Add atomic button classes in main.scss
- Update tutorial template

NOTE: added buttons in tutorial hero for examples

Screen Shot 2022-01-21 at 4 44 45 PM

### CODE REVIEW

**Review by ybyzek — CHANGES_REQUESTED** [review]
@scott-confluent thanks for the PR.

This PR is looking good:

- The side-by-side text with `introduction_media` looks awesome
- The buttons look nice.  I guess I have to choose one, right? :) 

Something to fix:

- The original tutorials (e.g. pick something like kafka-console-consumer-producer-basics/confluent.html) look weird with the text, see screenshot below. These are generated from `_layouts/tutorial.html`

Screen Shot 2022-01-21 at 18 48 10 PM

**Comment by scott-confluent** [comment]
> @scott-confluent thanks for the PR.
> 
> This PR is looking good:
> 
> * The side-by-side text with `introduction_media` looks awesome
> * The buttons look nice.  I guess I have to choose one, right? :)
> 
> Something to fix:
> 
> * The original tutorials (e.g. pick something like kafka-console-consumer-producer-basics/confluent.html) look weird with the text, see screenshot below. These are generated from `_layouts/tutorial.html`
> 
> Screen Shot 2022-01-21 at 18 48 10 PM

Still working on the tutorial layout. Just wanted to get this up so we could start the discussion.

Regarding the buttons in the tutorial hero, I think the primary looks like island button and the secondary would be the midnight with white outline.

**Comment by scott-confluent** [comment]
@ybyzek i've fixed the layout issues

**Review by ybyzek — APPROVED** [review]
🥳 @scott-confluent LGTM thank you!

**Pull request merged**
