### PR TITLE
DEVX-1559: Updates to Flatten Nested tutorial for ksql 0.7

### PR DESCRIPTION
**Pull request by bbejeck**

### CODE REVIEW

**Comment by rspurgeon** [comment]
In testing this PR I'm getting the following error:

```
ksql> SELECT
>    ID AS ORDER_ID,
>    TIMESTAMP AS ORDER_TS,
>    AMOUNT AS ORDER_AMOUNT,
>    CUSTOMER->FIRSTNAME AS CUST_FIRST_NAME,
>    CUSTOMER->LASTNAME AS CUST_LAST_NAME,
>    CUSTOMER->PHONENUMBER AS CUST_PHONE_NUMBER,
>    CUSTOMER->ADDRESS->STREET AS CUST_ADDR_STREET,
>    CUSTOMER->ADDRESS->NUMBER AS CUST_ADDR_NUMBER,
>    CUSTOMER->ADDRESS->ZIPCODE AS CUST_ADDR_ZIPCODE,
>    CUSTOMER->ADDRESS->CITY AS CUST_ADDR_CITY,
>    CUSTOMER->ADDRESS->STATE AS CUST_ADDR_STATE,
>    PRODUCT->SKU AS PROD_SKU,
>    PRODUCT->NAME AS PROD_NAME,
>    PRODUCT->VENDOR->VENDORNAME AS PROD_VENDOR_NAME,
>    PRODUCT->VENDOR->COUNTRY AS PROD_VENDOR_COUNTRY
>FROM
>    ORDERS
>EMIT CHANGES
>LIMIT 4;
+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+
|ORDER_ID  |ORDER_TS  |ORDER_AMOU|CUST_FIRST|CUST_LAST_|CUST_PHONE|CUST_ADDR_|CUST_ADDR_|CUST_ADDR_|CUST_ADDR_|CUST_ADDR_|PROD_SKU  |PROD_NAME |PROD_VENDO|PROD_VENDO|
|          |          |NT        |_NAME     |NAME      |_NUMBER   |STREET    |NUMBER    |ZIPCODE   |CITY      |STATE     |          |          |R_NAME    |R_COUNTRY |
+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+
|1         |2020-01-18|84.02     |Ricardo   |Ferreira  |1234567899|Street SDF|8602      |27640     |Raleigh   |NC        |P12345    |Highly Dur|Acme Corp |US        |
|          | 01:12:05 |          |          |          |          |          |          |          |          |          |          |able Glue |          |          |
|2         |2020-01-18|84.02     |Tim       |Berglund  |9987654321|Street UOI|1124      |85756     |Littletown|CO        |P12345    |Highly Dur|Acme Corp |US        |
|          | 01:35:12 |          |          |          |          |          |          |          |          |          |          |able Glue |          |          |
|3         |2020-01-18|84.02     |Robin     |Moffatt   |4412356789|Street YUP|9066      |BD111NE   |Leeds     |YS        |P12345    |Highly Dur|Acme Corp |US        |
|          | 01:58:55 |          |          |          |          |          |          |          |          |          |          |able Glue |          |          |
Fatal user code error in TimestampExtractor callback for record ConsumerRecord(topic = ORDERS, partition = 0, leaderEpoch = null, offset = 4, CreateTime = 1583268731528, serialized key size = -1, serialized value size = 0, headers = RecordHeaders(headers = [], isReadOnly = false), key = null, value = null).
Caused by: java.lang.NullPointerException
Query terminated
```

**Comment by bbejeck** [comment]
>In testing this PR I'm getting the following error:
@rspurgeon  working on fixing this now

**Comment by bbejeck** [comment]
@rspurgeon I tried to use only one `ksqlDB` terminal window, and that seemed to work, but the test harness doesn't like that approach, it needs a second terminal window to get opened up.

I ran through the tutorial as is again, and I was successful, the only change is that I copied all the input for the console producer vs. one line at a time.  Not sure if that even makes sense, but it worked this time through.

**Comment by bbejeck** [comment]
\cc @colinhicks  for this

**Comment by bbejeck** [comment]
Thanks for the review @rspurgeon!

**Pull request merged**
