### PR TITLE
Handling Deserialization Errors (KSQL)

### PR DESCRIPTION
**Pull request by riferrei**
This tutorial showcase the `KSQL Processing Log` feature, that allows developers to easily and quickly identify any deserialization errors that might have happened when events were produced to a stream and/or table.

This PR addresses the following issue: https://github.com/confluentinc/kafka-tutorials/issues/179

Sincerely,

-- @riferrei

### CODE REVIEW

**Comment by riferrei** [comment]
Hey @colinhicks, is there any plans to have this tutorial merged?

**Comment by colinhicks** [comment]
@riferrei Thanks for the ping. I apologize for losing track of this review request. Also, feel free to ask others for a review :).

At a glance this looks very close, but we'll want to bring this up to date with ksqlDB 0.8.1. I can take a deeper look toward the end of the week.

**Comment by gAmUssA** [comment]
@riferrei is it up to date and ready for review? I will be able to review

**Comment by riferrei** [comment]
> @riferrei is it up to date and ready for review? I will be able to review

Yes. It should be good to go for reviewing purposes.

**Comment by riferrei** [comment]
Cool, thanks @gAmUssA. I will upgrade the CP version before merge.

**Comment by gAmUssA** [comment]
can we include this in release @colinhicks @bbejeck ?

**Comment by bbejeck** [comment]
> can we include this in release @colinhicks @bbejeck ?
Yep

**Pull request merged**
