### PR TITLE
[MINOR] Maintain consistency in KT titles on the cards

### PR DESCRIPTION
**Pull request by ybyzek**
### Description

- Maintain consistency in KT titles on the cards on the main KT page
- Moved ~2 KTs to a different card (this can be undone if anyone disagrees with the new placement)

### Staging Docs

http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/card_titles_consistency/

### CODE REVIEW

**Review by bbejeck — APPROVED** [review]
Overall LGTM, I'm not 100% sure that `Callbacks` goes under `Build Applications`, but I also don't have a strong opinion on it, so I'm fine either way.

**Comment by ybyzek** [comment]
> I'm not 100% sure that Callbacks goes under Build Applications, but I also don't have a strong opinion on it, so I'm fine either way.

@awalther28 -- any leaning on the comment from @bbejeck ?  I also can go either way.

**Comment by awalther28** [comment]
@ybyzek I personally think callbacks is okay under build applications.

**Comment by ybyzek** [comment]
As discussed in Slack, ok to merge.

**Pull request merged**
