### PR TITLE
Kafka Tutorials Release [October 11, 2021]

### PR DESCRIPTION
**Pull request by ybyzek**
### Description

- https://github.com/confluentinc/kafka-tutorials/pull/956
- https://github.com/confluentinc/kafka-tutorials/pull/959
- https://github.com/confluentinc/kafka-tutorials/pull/960

### Staging Docs

http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master

### CODE REVIEW

**Comment by ybyzek** [comment]
> @ybyzek the [first producer](http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master/creating-first-apache-kafka-producer-application/confluent.html) and [first consumer](http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master/creating-first-apache-kafka-consumer-application/confluent.html) links are difficult to get the correct spot to click on - I didn't check these two in particular for the original PR. The links work, but you need to move around a little. They still work, but you have to hit the exact spot. It's minor so I'll leave it up to you for merging or not.

@bbejeck that's very strange but I can reproduce it as well.  The difference between those tutorials is the presence of a short answer, and I have no idea how/why that impacts the link.

@danshafie do you have any insight as to what this issue is and how to fix?

Specifically: note the difference between these two tutorials below on where you have to click "here" in `New to Confluent Cloud? Sign up here and then run this tutorial.`

http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master/kafka-console-consumer-producer-basics/confluent.html
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master/creating-first-apache-kafka-producer-application/confluent.html

**Comment by ybyzek** [comment]
@danshafie thanks for the explanation and the visual.  IIUC the next section is encroaching on this one and covering up the sentence/link a bit, but I'm afraid I don't understand what the fix would be.  Do you know?

**Comment by danshafie** [comment]
> @danshafie thanks for the explanation and the visual. IIUC the next section is encroaching on this one and covering up the sentence/link a bit, but I'm afraid I don't understand what the fix would be. Do you know?

sorry. you can add `margin-top: 0` to the class name `columns`, but since this looks to be a template, it would be good to make sure this doesnt have weird side effects elsewhere.

**Comment by ybyzek** [comment]
@danshafie the only place I see `columns` defined is in `node_modules`, but that's ignored (https://github.com/confluentinc/kafka-tutorials/blob/master/.gitignore#L10) -- it's installed locally.  So it's not clear to me that we can override that template with the current setup.

**Comment by ybyzek** [comment]
I propose https://github.com/confluentinc/kafka-tutorials/pull/958/files as the fix since it uses div instead of BR (latter seems hackier)

**Comment by bbejeck** [comment]
> I'm inclined to wait on this release until the other 2 open PRs are reviewed/merged, if that's ok.

Makes sense, that works for me.

**Pull request merged**
