### PR TITLE
KAFKA TUTORIALS [Release 11-23-2020] 

### PR DESCRIPTION
**Pull request by bbejeck**
### Description

This is a minor release which includes some fixes and one new tutorial

### Staging Docs

Staged at http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master/

### CODE REVIEW

**Comment by ybyzek** [comment]
@bbejeck I didn't review the nested JSON KT PR, so this feedback is late, but is the title incorrect because it has `ksqlDB` in the title?

**Comment by bbejeck** [comment]
> I didn't review the nested JSON KT PR, so this feedback is late, but does the title in http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master/ksqldb-working-with-nested-json/ksql.html need to be modified to remove ksqlDB from it?

@ybyzek ack.  I'll do a minor PR now to fix that.

**Comment by ybyzek** [comment]
@bbejeck would it be possible to get https://github.com/confluentinc/kafka-tutorials/pull/644 into this release?

**Comment by bbejeck** [comment]
> would it be possible to get #644 into this release? 

@ybyzek Absolutely, no issue at all.

**Review by ybyzek — APPROVED** [review]
LGTM

**Comment by bbejeck** [comment]
released via https://github.com/confluentinc/kafka-tutorials/commit/a6bd1dccf32bfb21b38a24a4df7bc0d9ef9cdd7f

**Pull request merged**
