### PR TITLE
KT release [1-25-2023]

### PR DESCRIPTION
**Pull request by TerryDevS**

### CODE REVIEW

**Comment by TerryDevS** [comment]
@davetroiano @bbejeck It seems like many conflicts between `release` and `master`. Can you guys take a look at this? Thank you!

Screen Shot 2023-01-24 at 2 53 23 PM

**Comment by bbejeck** [comment]
@TerryDevS  the conflicts are resolved, and the [release is completed ](https://confluentinc.semaphoreci.com/workflows/c8bf8c64-8a9c-48be-875e-86a2a1fce0ce?pipeline_id=ddc34d54-f863-4158-ab22-b771b3d2111b)

**Comment by TerryDevS** [comment]
@bbejeck It seems like `CI` is failing ? should it be re-triggered ?

**Comment by bbejeck** [comment]
The errors were unrelated - I manually pushed the release out

**Pull request merged**
