### PR TITLE
Update release process

### PR DESCRIPTION
**Pull request by ybyzek**
### Description

Update README with more details on how to release to the live site

Documentation changes only

### CODE REVIEW

**Review by bbejeck — APPROVED** [review]
Thanks for this update @ybyzek LGTM!

**Comment by bbejeck** [comment]
Looks like this PR exposed something unrelated that needs to be fixed 
```
pkg_resources.DistributionNotFound: The 'harness-runner==0.0.1' distribution was not found and is required by the application
```
But we should take this up in a separate PR

**Comment by ybyzek** [comment]
👍 I have filed https://github.com/confluentinc/kafka-tutorials/issues/1308 to track the issue with the harness runner

**Review by davetroiano — APPROVED** [review]
LGTM!

**Pull request merged**
