### PR TITLE
MINOR: Update text for question and details

### PR DESCRIPTION
**Pull request by bbejeck**
### Staging Docs

http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/MINOR_update_nested_JSON_tutorial_language/
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/MINOR_update_nested_JSON_tutorial_language/working-with-nested-json/ksql.html

### CODE REVIEW

**Comment by bbejeck** [comment]
ping @ybyzek for review

**Comment by bbejeck** [comment]
test for nested JSON tutorial passed

**Review by ybyzek — APPROVED** [review]
LGTM @bbejeck

**Comment by bbejeck** [comment]
thanks for the review @ybyzek

**Pull request merged**
