### PR TITLE
Live site release, week of Feb 3, 2020

### PR DESCRIPTION
**Pull request by colinhicks**
New tutorials 🎉:
* KStreams - finding distinct events 
* KStreams - connect JDBC specific avro 
* KStreams - emit a final result from a time window
* KSQL - User defined functions
* KSQL - hopping windows 
* KSQL - finding distinct events 
* KSQL - flatten nested data

The large diff is due to the fact that I squashed the previous merge into `release` :/. Starting with this PR, we should use merge commits into the `release` branch instead.

Review changes here: http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master/c710115f3a0350e93c9e680d5544322dfeda677d/

**Tutorials have been separately reviewed in individual PRs, so the review ask here is focused on the rendering of the staging site linked above.** Thanks for taking a look!

### CODE REVIEW

**Comment by colinhicks** [comment]
Re-enabled merge commits (for now at least).

**Comment by colinhicks** [comment]
Changes staged here: http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master/e38d0c6dfbde1d96c5e450c876a9d705ed1883ea/

**Comment by colinhicks** [comment]
Updated staging link http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master/c710115f3a0350e93c9e680d5544322dfeda677d/

**Comment by colinhicks** [comment]
The connect-jdbc-avro test is failing consistently in CI. I was able to reproduce the failure locally. Looking into it.

**Comment by colinhicks** [comment]
I was able to improve the connect-jdbc-avro test so that the consumer output matches what's expected. The test now works consistently locally. The main assertion also passes in Semaphore, returning with exit code 0 and `export SEMAPHORE_JOB_RESULT=passed`.

Despite this, the Semaphore container does not fully shut down, and the Semaphore task times out. Looks like the JVM is running out of memory, from the latest run:
`Native memory allocation (mmap) failed to map 43515904 bytes for committing reserved memory.`

For this review, we mostly care about the site rendering and the tutorials working properly on a local machine. I will continue debugging Semaphore, but I am not sure whether we want to block this release on the flaky test.

**Comment by rspurgeon** [comment]
Staging site LFGTM!  Are there any particular changes you're worried about risk you'd like someone to spot check (Particualr tutorials, etc)?

**Comment by colinhicks** [comment]
Thanks for taking a look, @rspurgeon. I think just a spot check on rendering is okay since we've had a pass at the changes already in the PRs into master.

**Comment by colinhicks** [comment]
Blocked by https://github.com/confluentinc/kafka-tutorials/issues/200

**Pull request merged**
