### PR TITLE
Extend wait-for-containers.sh to check Connect status

### PR DESCRIPTION
**Pull request by ybyzek**
### Description

#903 

### Staging Docs

http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/GH-903
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/GH-903/connect-add-key-to-source/kstreams.html

### CODE REVIEW

**Review by bbejeck — APPROVED** [review]
Thanks for the fix @ybyzek, LGTM waiting for tests to pass then we can merge.

**Comment by ybyzek** [comment]
@bbejeck So far I think this PR provides a partial fix: it's no longer exhibiting the error with the connector REST endpoint not being ready, but I haven't seen a full PASS yet.

**Comment by ybyzek** [comment]
@bbejeck `connect-add-key-to-source` now passes.  The test failure is unrelated.  🎉

**Comment by bbejeck** [comment]
@ybyzek - nice work!

**Pull request merged**
