### PR TITLE
Add new recipe for ML model retraining

### PR DESCRIPTION
**Pull request by ybyzek**
### Description

New recipe port over

### Staging Docs

http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/model_retraining_recipe/model-retraining/confluent.html

### CODE REVIEW

**Review by rspurgeon — APPROVED** [review]
I validated the code works, my only feedback is the formatting of the field names. The quoted names seem unnecessary (are they for some reason?) and not consistent with the other recipes.

**Comment by ybyzek** [comment]
> I validated the code works, my only feedback is the formatting of the field names. The quoted names seem unnecessary (are they for some reason?) and not consistent with the other recipes.

@rspurgeon can you please elaborate?  An example of how it's in this recipe versus an example of how it's in other recipes?

**Comment by rspurgeon** [comment]
> > I validated the code works, my only feedback is the formatting of the field names. The quoted names seem unnecessary (are they for some reason?) and not consistent with the other recipes.
> 
> @rspurgeon can you please elaborate? An example of how it's in this recipe versus an example of how it's in other recipes?

```
CREATE STREAM predicted_weight(
  "Fish_Id" VARCHAR KEY,
  "Species" VARCHAR,
  "Height" DOUBLE,
  "Length" DOUBLE,
  "Prediction" DOUBLE
  )
```

I don't see other queries that have these "quoted names"

**Comment by ybyzek** [comment]
I agree, thanks for calling this out @rspurgeon .  I'm guessing @daveklein went this way for consistency with the blog post, but it's probably more useful to have consistency with other recipes at this point. @daveklein any concern if I modify this (remove quotes, etc)?

**Comment by ybyzek** [comment]
@rspurgeon @daveklein https://github.com/confluentinc/kafka-tutorials/pull/1064/commits/7839cd57130e3416ff8f38ed9f5d65b840312ea7 has the cleaned up statements

**Pull request merged**
