### PR TITLE
Updated logo

### PR DESCRIPTION
**Pull request by TerryDevS**
### Description

Updated logo.

### Staging Docs

http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/update-nav-logo

### CODE REVIEW

**Review by ybyzek — COMMENTED** [review]
@TerryDevS `master` may not be the right target branch.  Should it be `tutorials`?  Because it's `tutorials` that migrates KT to CD.  cc: @hartantothio

**Comment by TerryDevS** [comment]
> @TerryDevS `master` may not be the right target branch. Should it be `tutorials`? Because it's `tutorials` that migrates KT to CD. cc: @hartantothio

@ybyzek Thank for catching it! I will confirm with @hartantothio

**Comment by TerryDevS** [comment]
@hartantothio I am double checking that base branch should be tutorials.

**Comment by ybyzek** [comment]
@TerryDevS with the change in base branch, the branch itself needs to be rebased as well. Or recreate the branch with base branch `tutorials`

**Comment by TerryDevS** [comment]
> 
@ybyzek Will do that. Thank you!

**Pull request closed without merging**
