### PR TITLE
DEVX-2057: Fix bugs in clone script, improve kafka type support add sample props  to script itself, update README with better example

### PR DESCRIPTION
**Pull request by bbejeck**
- Fixed placement of checklist file
- Fixed bug where old directories copied over 
- Found and fixed bug where `sed` would choke over illegal characters
- Cleanup for supporting `kafka` type projects
- Added comments to top of `clone.sh` showing example properties to set
- Updated README with better examples

Covers #523 and #466

### CODE REVIEW

**Comment by bbejeck** [comment]
@gAmUssA I tried this out with `kafka` type tutorials and it seemed to work

**Review by ybyzek — CHANGES_REQUESTED** [review]
@bbejeck Thanks!

From https://github.com/confluentinc/kafka-tutorials/issues/466, this PR addresses issue 1 and 2.

However, issue 3 appears to be unaddressed.  For example, cloning `garbage1` from `window-final-result` results in:

```
[8:39:40] ~/git/kafka-tutorials/_includes/tutorials(DEVX_2057_fix_clone_bugs) ✗: ls window-final-result/         
total 0
drwxr-xr-x  3 yeva staff   96 Feb 28  2020 .
drwxr-xr-x 41 yeva staff 1312 Sep 21 08:36 ..
drwxr-xr-x  4 yeva staff  128 Feb 28  2020 kstreams
[8:39:48] ~/git/kafka-tutorials/_includes/tutorials(DEVX_2057_fix_clone_bugs) ✗: ls garbage1 
total 4
drwxr-xr-x  4 yeva staff  128 Sep 21 08:36 .
drwxr-xr-x 41 yeva staff 1312 Sep 21 08:36 ..
-rw-r--r--  1 yeva staff  634 Sep 21 08:36 garbage1_checklist.txt
drwxr-xr-x  3 yeva staff   96 Sep 21 08:36 window-final-result
```

Here is the input properties file that generated the above output:

```
# By using the basename of a tutorial everything is cloned possibly ksql, kstreams, and kafka
ORIG_TUTORIAL=window-final-result

# Add a new tutorial name
NEW_TUTORIAL=garbage1
# Add a new sempahore test name
SEMAPHORE_TEST_NAME="Garbage1 Semaphore"
# Add a new PERMALINK
PERMALINK=garbage1-permalink
```

**Comment by ybyzek** [comment]
Potential fix for issue 3

```
[9:54:25] ~/git/kafka-tutorials(DEVX_2057_fix_clone_bugs) ✗: git diff tools/clone-tutorial.sh 
diff --git a/tools/clone-tutorial.sh b/tools/clone-tutorial.sh
index 463cee7f..ebed031f 100755
--- a/tools/clone-tutorial.sh
+++ b/tools/clone-tutorial.sh
@@ -104,7 +104,7 @@ if [ ! -d "${TUTORIALS_DIR}/${NEW_TUTORIAL}" ]; then
 fi
 echo "Copying tutorial files from ${TUTORIALS_DIR}/${ORIG_CLONE_FILES_DIR} to ${TUTORIALS_DIR}/${NEW_TUTORIAL_DIR}"
-cp -R $TUTORIALS_DIR/$ORIG_CLONE_FILES_DIR/ $TUTORIALS_DIR/$NEW_TUTORIAL_DIR
+cp -R $TUTORIALS_DIR/$ORIG_CLONE_FILES_DIR/. $TUTORIALS_DIR/$NEW_TUTORIAL_DIR
 if [ ! -z "${SINGLE_TYPE_CLONE}" ]; then
        if [ ! -d $TEST_HARNESS_DIR/$NEW_TUTORIAL ]; then
```

**Comment by bbejeck** [comment]
@ybyzek updated with suggested fix, works for me locally

**Review by ybyzek — APPROVED** [review]
LGTM!  Thanks @bbejeck

**Pull request merged**
