### PR TITLE
KT release [November 21, 2022]

### PR DESCRIPTION
**Pull request by TerryDevS**
### Description
Segment tracking for scrollDepth. #1455 

### Staging Docs

http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master

### CODE REVIEW

**Comment by TerryDevS** [comment]
Hi @davetroiano I made this Release request PR and I see a test failure which did not fail with my PR(#1455 ). Could you take a look ?

**Comment by davetroiano** [comment]
> Hi @davetroiano I made this Release request PR and I see a test failure which did not fail with my PR(#1455 ). Could you take a look ?
> 
> https://confluentinc.semaphoreci.com/jobs/bb7ab676-ea36-4cdf-8bcf-928fad163443

hi @TerryDevS that looks like a flake - since the build [here](https://confluentinc.semaphoreci.com/workflows/1972fef8-d4d0-483b-b956-ddb700bc6202?pipeline_id=d09ddc15-7769-4384-b11e-3c23b82103ee) passed, this is good to merge once you confirm that al looks good on the segment side (I'm not sure how to validate that)

**Review by davetroiano — APPROVED** [review]

**Comment by TerryDevS** [comment]
@davetroiano It seems like I am not able to `merge` since it requires statuses must pass. I will re run the pipeline.

**Comment by davetroiano** [comment]
> @davetroiano It seems like I am not able to `merge` since it requires statuses must pass. I will re run the pipeline.

no worries - I bypassed that and merged. will keep an eye on the release build so that it gets deployed to prod

**Comment by TerryDevS** [comment]
@davetroiano  Thanks a lot!

**Pull request merged**
