### PR TITLE
MINOR: Update the KT landing page

### PR DESCRIPTION
**Pull request by bbejeck**
This PR moves the `Kafka 101` card to the upper left-hand corner and allows for expanding/contracting the large tutorial list in `Apply a function to data`

### CODE REVIEW

**Comment by bbejeck** [comment]
Staged at 

http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/MINOR_update_landing_page/4d1c8270322fdb0f2053fb70d989afdf03ada97c/

ping one of @ybyzek @rspurgeon @gAmUssA @colinhicks  for a review and +1

**Comment by gAmUssA** [comment]
love it!

**Comment by rspurgeon** [comment]
I agree this is great.  one bit of feedback is that the clipping is pretty tight on my screen.  There isn't much of a margin around the outer edge and the second row of boxes.

Screen Shot 2020-06-02 at 1 48 10 PM

**Comment by bbejeck** [comment]
>one bit of feedback is that the clipping is pretty tight on my screen. There isn't much of a margin around the outer edge and the second row of boxes.

Yeah, good point.  I've tried something out and moved the CTA card to a third row.
Check this out and let me know

http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/MINOR_update_landing_page/aff0db826473148b0d63dd58048f5036cc1f3e69/

\cc @rspurgeon

**Comment by rspurgeon** [comment]
> Yeah, good point. I've tried something out and moved the CTA card to a third row.
> Check this out and let me know

That looks great to me!

**Comment by bbejeck** [comment]
Thanks for the review @rspurgeon!

**Pull request merged**
