### PR TITLE
KT release [03/04/2021]

### PR DESCRIPTION
**Pull request by ybyzek**
### Description

This PR does cover a lot of files but no new tutorials, just minor fixes.  

- Dependabot version updates
- Updated links
- Connector REST API for the existing datagen KT
- New short answers
- broker-list --> bootstrap-server
- Minor spelling and text changes

### Staging Docs

http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master/

Check: http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master/how-to-count-messages-on-a-kafka-topic/ksql.html should show 2 tutorials (ksqlDB and KStreams), each with short answers

### CODE REVIEW

**Review by bbejeck — APPROVED** [review]

**Comment by bbejeck** [comment]
kicked off tests again just for a sanity check

**Comment by ybyzek** [comment]
Note: 

1. Test failure in a KT that was not touched by this PR.  
2. Do we know how to interpret the [failure](https://confluentinc.semaphoreci.com/jobs/3d7f899b-ebe2-43f9-8987-63942d055d7a) which doesn’t seem to have an error message?

**Comment by bbejeck** [comment]
Failure in https://confluentinc.semaphoreci.com/jobs/3d7f899b-ebe2-43f9-8987-63942d055d7a was from the test timing out.  We have a few ksqlDB tests that timeout,  the solution so far has been to re-run the tests.

**Comment by ybyzek** [comment]
(note: local run of the failed test passes)

As discussed in Slack, merging PR.

**Pull request merged**
