### PR TITLE
CCloudify Tumbling Windows

### PR DESCRIPTION
**Pull request by ybyzek**
### Description

* CCloudify Tumbling Windows

Note there is a warning now in the code that I'm not sure if it's something needing addressed:

```
> Task :_includes:tutorials:tumbling-windows:kstreams:code:compileJava
Note: /Users/yeva/git/kafka-tutorials/_includes/tutorials/tumbling-windows/kstreams/code/src/main/java/io/confluent/developer/TumblingWindow.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :_includes:tutorials:tumbling-windows:kstreams:code:compileTestJava
Note: /Users/yeva/git/kafka-tutorials/_includes/tutorials/tumbling-windows/kstreams/code/src/test/java/io/confluent/developer/TumblingWindowTest.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

I added this into the build:

```
  tasks.withType(JavaCompile) {
      options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
  }
```

and it shows below.  However, adding `Map<String,String>` does not fix it.  Looking for advice whether code should be left as-is or suggestions on how to address. 

```
> Task :_includes:tutorials:tumbling-windows:kstreams:code:compileJava FAILED
/Users/yeva/git/kafka-tutorials/_includes/tutorials/tumbling-windows/kstreams/code/src/main/java/io/confluent/developer/TumblingWindow.java:84: warning: [unchecked] unchecked conversion
        final Map<String, String> serdeConfig = (Map)allProps;
                                                ^
  required: Map<String,String>
  found:    Map
```

### Staging Docs

http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/ccloud-tumbling-windows/create-tumbling-windows/confluent.html

### CODE REVIEW

**Review by rspurgeon — APPROVED** [review]
LGTM

**Comment by ybyzek** [comment]
@bbejeck @rspurgeon the test case that is failing does not appear to be related to this PR.

But before merging, any thoughts on the warning message in the description?

**Comment by ybyzek** [comment]
Thanks to @bbejeck for the suggestion on addressing the compiler warning: https://github.com/confluentinc/kafka-tutorials/pull/795/commits/9eb5d3dd9a0202bedc05e3384cfd5d08b38b8302

**Review by bbejeck — APPROVED** [review]
LGTM

**Comment by bbejeck** [comment]
All tests passed!

**Pull request merged**
