### PR TITLE
MINOR: update docker-compose templates to support networks

### PR DESCRIPTION
**Pull request by bbejeck**
This PR updates the `docker-compose.yml` templates to support docker networking

### CODE REVIEW

**Comment by colinhicks** [comment]
This seems to be more about naming the network that docker-compose creates, and less about _supporting networks_ – they are already supported by all our current compose files, which create a network with a random name.

Is the goal to have a common Docker network name across all tutorials? Does this PR propose other advantages?

**Comment by bbejeck** [comment]
@colinhicks - good point.  

I'm somewhat neutral on this PR as it's a follow-up from comments on https://github.com/confluentinc/kafka-tutorials/pull/295 regarding changes to docker-compose.

@gAmUssA any additional comments?

**Comment by gAmUssA** [comment]
@colinhicks Motivation for specific network name - we can reference this name in the section when we're talking about docker image. Without consistent network naming, it would be hard to write a reproducible harness scenario.

**Comment by colinhicks** [comment]
Thanks for the explanation, @gAmUssA. I'm still a bit unclear on when we would refer to a Docker network name in the tutorial text content. Is there an example where we are currently doing this – or should be ideally? I think I overlooked the specific comments in #295 where this came up.

> Without consistent network naming, it would be hard to write a reproducible harness scenario.

Is there something that is currently not working because the network name is inconsistent?

One of the nice things about docker-compose is that it abstracts some of the complexity of dealing with Docker. It seems like its default networking behavior has served the tutorials well so far. My suggestion is that we only add explicit networking configuration in cases where it makes the tutorial easier and/or less error-prone for the reader, overall.

**Comment by gAmUssA** [comment]
@colinhicks check this one https://kafka-tutorials.confluent.io/aggregating-average/kstreams.html#launch-the-container

**Comment by colinhicks** [comment]
Thanks, @gAmUssA. I understand now :). This change does make sense for the cases where we are building separate a Docker image for the application. The application container needs to join the network created by the docker-compose config, which is easiest to do when the network has an explicit name.

**Comment by rspurgeon** [comment]
It's possible that having the same network name across all tutorials could pose some issues or confusion for users wanting to run multiple tutorials.  This may not be an issue for us as we specify explicit service names, but I just wanted to broach the idea of obtaining the network name at runtime instead of statically defining it.  One way may be using `yq` which requires a small image pull: 

```
docker run --rm -v "${PWD}":/workdir mikefarah/yq yq r docker-compose.yml 'networks.cp.name'
cp_network
```

we could repackage `yq` into a cnfl controlled image if need be.  Just an idea to float...

**Comment by rspurgeon** [comment]
I keep getting reminders on this stale PR... can we close it or move forward?  @bbejeck

**Comment by bbejeck** [comment]
closing for now and we can re-visit at a later time if we feel the need.

**Comment by gAmUssA** [comment]
What's required to make this default?

**Pull request closed without merging**
