### PR TITLE
MINOR: Updates for user to not create directory

### PR DESCRIPTION
**Pull request by bbejeck**
### Description

Removing the step for users to create a directory, but still have it for the harness-runner.

### Staging Docs

 http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/MINOR_fix_avro_tutorial/
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/MINOR_fix_avro_tutorial/kafka-console-consumer-producer/kafka.html

### CODE REVIEW

**Comment by bbejeck** [comment]
Found an unrelated issue causing the build failure - working on it.

**Comment by bbejeck** [comment]
I'm working on a fix for the build but the PR is still reviewable

**Review by rspurgeon — APPROVED** [review]
LGTM

**Comment by bbejeck** [comment]
Test failures unrelated to this PR

**Pull request merged**
