### PR TITLE
IoT asset tracking ksqlDB tutorial (#1287)

### PR DESCRIPTION
**Pull request by davetroiano**
* marketing copy edits
* rename "loss tracking" to more familiar "asset tracking"

### Description

https://github.com/confluentinc/kafka-tutorials/issues/1287

### Staging Docs

http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/iot-asset-tracking-copy-edits/
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/iot-asset-tracking-copy-edits/iot-asset-tracking/confluent.html

### Updated tutorial checklist

 - [x] Implement good test cases (if relevant)
 - [x] Validate hyperlinks
 - [x] Spell check (e.g. using `aspell`)
 - [x] Full code validated in Confluent Cloud
 - [x] SQL style/syntax consistent to existing recipes
 - [x] Validate presentation with `bundle exec jekyll serve --livereload`
 - [x] Tutorial added to appropriate `index.html` or `use-case.html` file
 - [x] Source connector's auto topic naming convention works with the ksqlDB app values for `KAFKA_TOPIC` (if relevant)

### CODE REVIEW

**Review by ybyzek — COMMENTED** [review]
@davetroiano for your consideration: change the title cosmetically but not the URL (otherwise all assets that point to this need to be updated and a redirect needs to be added)

**Comment by davetroiano** [comment]
@ybyzek isn't this ok since it hasn't been released yet?

**Comment by ybyzek** [comment]
> @ybyzek isn't this ok since it hasn't been released yet?

Yes indeed!  I lost track that it wasn't released yet.  My apologies...

**Comment by davetroiano** [comment]
> Yes indeed! I lost track...
pun?  :)

I'll release after this is merged

**Review by bbejeck — APPROVED** [review]
LGTM!

**Pull request merged**
