### PR TITLE
Kafka Tutorials Release [February 10, 2022]

### PR DESCRIPTION
**Pull request by ybyzek**
### Description

Numerous small improvements, including but not limited to:

- https://github.com/confluentinc/kafka-tutorials/pull/1075
- https://github.com/confluentinc/kafka-tutorials/pull/1069
- https://github.com/confluentinc/kafka-tutorials/pull/1065
- https://github.com/confluentinc/kafka-tutorials/pull/1064
- https://github.com/confluentinc/kafka-tutorials/pull/1063
- https://github.com/confluentinc/kafka-tutorials/pull/1062

### Staging Docs

http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master

### CODE REVIEW

**Comment by rspurgeon** [comment]
@ybyzek I might be missing it, but I don't think i see the images in the staged version

**Comment by rspurgeon** [comment]
@ybyzek is it intentional that the two new recipes are not linked from the use case recipes home page?

**Comment by ybyzek** [comment]
> @ybyzek is it intentional that the two new recipes are not linked from the use case recipes home page?

This is expected.  They are not linked from use-cases.html but they are linked from use-cases-phase2.html

**Review by rspurgeon — APPROVED** [review]

**Review by bbejeck — APPROVED** [review]
LGTM

**Pull request merged**
