### PR TITLE
Kafka Tutorials Release [May 11, 2022] 

### PR DESCRIPTION
**Pull request by bbejeck**
### Description

Includes the following:

- #1256 
- Upgrade all tutorials (Java based) to use Gradle version 7.4.2
- Reorder steps to promote `INSERT INTO` over connector (https://github.com/confluentinc/kafka-tutorials/pull/1259 and https://github.com/confluentinc/kafka-tutorials/pull/1260)
- Other small fixes

### CODE REVIEW

**Comment by ybyzek** [comment]
@bbejeck thank you for following up on this release so quickly.  FYI https://github.com/confluentinc/kafka-tutorials/pull/1264 seems to be getting close to being ready and it impacts the nav, perhaps we can wait on that PR, assuming it will be reviewed/merged in the next day or so.

**Comment by ybyzek** [comment]
@bbejeck actually, that PR probably still needs more review time from various folks and I don't know their availability to close on it.  Sorry to reverse, I no longer think this PR should be blocked by that one.

**Review by ybyzek — APPROVED** [review]
LGTM, verified on desktop Safari & Chrome

**Comment by bbejeck** [comment]
only one test failure (unrelated)

**Pull request merged**
