### PR TITLE
Kafka Tutorials Release [07-27-2021]: Re-skin of site

### PR DESCRIPTION
**Pull request by bbejeck**
### Staging Docs

http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master/

### CODE REVIEW

**Comment by bbejeck** [comment]
Failures are from known flaky tests

**Comment by ybyzek** [comment]
@bbejeck `_includes/tutorials/connect-add-key-to-source/kstreams/` is failing, which you said is a known flakey test.  But there was also a change in this PR for that one KT.  The error for that test looks inconclusive.  Do we know for certain that this KT *can* pass (can you rerun the build or validate locally) and that this PR doesn't break it?

**Comment by bbejeck** [comment]
>The error for that test looks inconclusive. Do we know for certain that this KT can pass (can you rerun the build or validate locally) and that this PR doesn't break it?

I don't know, let me check

**Review by ybyzek — APPROVED** [review]
@bbejeck agree to merge this through.  Let's get a separate GH issue to track the flaky test so we can make it pass consistently & deterministically.

**Pull request merged**
