### PR TITLE
Update ksqlDB version to 0.8.1

### LINKED ISSUE #288: Update ksqlDB tutorials to v0.8.0

### PR DESCRIPTION
**Pull request by colinhicks**
Closes #288

### CODE REVIEW

**Comment by colinhicks** [comment]
Ready for review. All ksqlDB tests passed in the [last run](https://confluentinc.semaphoreci.com/workflows/d409f401-bb08-4620-a25d-1fdf5ac2b62f).

This version update was a big win for verification through self-testability. And it amortizes the investment we put into updating the tutorials for the new syntax in the last release.

To the review the PR, I propose we visually spot-check the ksqlDB tutorials with the changes staged here: https://confluentinc.semaphoreci.com/workflows/d409f401-bb08-4620-a25d-1fdf5ac2b62f. Otherwise, I think we are covered by the harness runner for the core functionality.

**Comment by colinhicks** [comment]
Since the CI tests have validated these changes, I think this just needs a quick set of eyes over the changes before merging.

**Comment by gAmUssA** [comment]
57 files 😱

**Comment by bbejeck** [comment]
failures not related to this PR

**Pull request merged**
