### PR TITLE
chore: remove jib it's not needed anymore, remove zookeeper ref

### PR DESCRIPTION
**Pull request by bbejeck**
### Description

[asana 1](https://app.asana.com/0/1201951209538300/1205933628199614/f)

[asana 2](https://app.asana.com/0/1201951209538300/1205973304739854/f)

### CODE REVIEW

**Comment by bbejeck** [comment]
There's a [failing test](https://semaphore.ci.confluent.io/jobs/13ae7d5f-edef-4c3b-8e5f-50041ca6098b) related to the changes in this PR

**Comment by bbejeck** [comment]
Failures are unrelated to the changes in this PR

**Comment by bbejeck** [comment]
Failures unrelated [the test with new compose file passes](https://semaphore.ci.confluent.io/jobs/5a38f5fe-32fd-426f-be2e-af160e0112a7)

**Review by davetroiano — APPROVED** [review]
LGTM!

**Pull request merged**
