### PR TITLE
GH-461: Update Docker images to cp-kafka (#461), update Docker image versions (#478)

### PR DESCRIPTION
**Pull request by ybyzek**
Address #461  and #478 

* Replace cp-enterprise-kafka (now deprecated) with cp-kafka
* Removes Confluent-specific configuration parameters that are not part of cp-kafka

### CODE REVIEW

**Review by rmoff — APPROVED** [review]
LGTM 👍

**Comment by gAmUssA** [comment]
@ybyzek as far I remember metrics reporter needs to be explicitly disabled.
Like I used in my demos https://github.com/confluentinc/demo-scene/blob/65ba048ab92bef17921132bac6ee5c1120521be0/testing-streams/transforming-events/docker-compose.yaml#L33

**Comment by ybyzek** [comment]
> @ybyzek as far I remember metrics reporter needs to be explicitly disabled.
Like I used in my demos https://github.com/confluentinc/demo-scene/blob/65ba048ab92bef17921132bac6ee5c1120521be0/testing-streams/transforming-events/docker-compose.yaml#L33

@gAmUssA that shouldn't be necessary with `cp-kafka` (Confluent Metrics Reporter shouldn't be bundled with that).  Also, I validated a tutorial and it passed.

**Comment by gAmUssA** [comment]
Just for a test - do you see any __confluent created?

**Comment by ybyzek** [comment]
@gAmUssA with current configuration, there is no metrics topic:

```
[8:49:28] ~/git/kafka-tutorials/_includes/tutorials/tumbling-windows/kstreams/code(GH-461) ✗: docker-compose exec broker kafka-topics --bootstrap-server localhost:9092 --list        
__confluent.support.metrics
_schemas
```

But notice there is `__confluent.support.metrics`!  This is a surprise and we need to follow-up separately.  Adding:

```
KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
```

Prevents that topic from being created:

```
[8:50:35] ~/git/kafka-tutorials/_includes/tutorials/tumbling-windows/kstreams/code(GH-461) ✗: docker-compose exec broker kafka-topics --bootstrap-server localhost:9092 --list
_schemas
```

**Comment by ybyzek** [comment]
@gAmUssA Update: changing broker image from 5.5.0 to 6.0.0 results in expected behavior -- proactive support is not automatically enabled in cp-kafka, so current configurations work.  As a result, I'm going to modify this PR to also address https://github.com/confluentinc/kafka-tutorials/issues/478 as well

**Comment by rspurgeon** [comment]
Noting some other docker containers in the 5.5 series on this branch:

```
tools/docker-compose.override.yml
11:    image: confluentinc/cp-enterprise-control-center:5.5.0
30:    image: confluentinc/cp-server:5.5.0

_includes/tutorials/kafka-streams-schedule-operations/kstreams/code/Dockerfile
1:FROM confluentinc/cp-kafka-connect-base:5.5.0

_includes/tutorials/kafka-connect-datagen-local/kafka/code/Dockerfile
1:FROM confluentinc/cp-kafka-connect-base:5.5.0
```

Also noting we use this library across tutorials which might need to be updated (independently or here):

`implementation "io.confluent:kafka-streams-avro-serde:5.5.1"`

**Comment by ybyzek** [comment]
@rspurgeon good catch.  I have addressed the docker-compose and Dockerfile release bump to 6.0.0 in https://github.com/confluentinc/kafka-tutorials/pull/579/commits/af2f2c2893b88980eaeacf4eda49ee386bbe7bd1

As for the client release references (e.g. implementation "io.confluent:kafka-streams-avro-serde:5.5.1"), do you have a leaning whether those should be addressed in this PR or a different PR?

**Comment by rspurgeon** [comment]
> do you (or anyone else) have a leaning whether those should be addressed in this PR or a different PR?

I'm not certain how these libraries are used across the tutorials. One possible risk is if somehow they are referenced in the 6.0 images by version (where there will be 6.0 versions).  However, I would guess they are built into uber jars and it's probably fine to address separately.   But i'm not certain for sure.  If all the tests pass I gather it's fine to punt to other PR

**Comment by bbejeck** [comment]
> Also noting we use this library across tutorials which might need to be updated (independently or here):
> implementation "io.confluent:kafka-streams-avro-serde:5.5.1"

Another point to consider is the `kafka-streams-avro-serde:XXX` dependency pulls in the corresponding AK version of `kafka-clients` as a transitive dependency.  Kafka streams require `kafka-clients` as well, and those versions need to match.

So if we upgrade the serde versions to `6.0.0`, we'll need to make sure we update Kafka Streams to `2.6` as well. 

The previous versions of the serdes _should_  work ok with the newer version of SR, so I vote to upgrade in a separate PR.

**Review by bbejeck — APPROVED** [review]
Thanks for the PR @ybyzek LGTM

**Comment by bbejeck** [comment]
Actually I  just found an issue with one of the connect tutorials

```
 "message" : "Failed to find any class that implements Connector and which name matches 

io.confluent.connect.jdbc.JdbcSourceConnector, available connectors are: PluginDesc{klass=class org.apache.kafka.connect.tools.MockConnector, 
name='org.apache.kafka.connect.tools.MockConnector', 
version='6.1.0-ccs-beta200715032424-hf-1', encodedVersion=6.1.0-ccs-beta200715032424-hf-1, type=connector, typeName='connector', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSinkConnector, name='org.apache.kafka.connect.tools.MockSinkConnector', version='6.1.0-ccs-beta200715032424-hf-1', encodedVersion=6.1.0-ccs-beta200715032424-hf-1, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSourceConnector, name='org.apache.kafka.connect.tools.MockSourceConnector', version='6.1.0-ccs-beta200715032424-hf-1', encodedVersion=6.1.0-ccs-beta200715032424-hf-1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.SchemaSourceConnector, name='org.apache.kafka.connect.tools.SchemaSourceConnector', version='6.1.0-ccs-beta200715032424-hf-1', encodedVersion=6.1.0-ccs-beta200715032424-hf-1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSinkConnector, name='org.apache.kafka.connect.tools.VerifiableSinkConnector', version='6.1.0-ccs-beta200715032424-hf-1', encodedVersion=6.1.0-ccs-beta200715032424-hf-1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSourceConnector, name='org.apache.kafka.connect.tools.VerifiableSourceConnector', version='6.1.0-ccs-beta200715032424-hf-1', encodedVersion=6.1.0-ccs-beta200715032424-hf-1, type=source, typeName='source', location='classpath'}"
```

**Comment by ybyzek** [comment]
Good catch @bbejeck .  I know what the issue is: in 6.0.0, all connectors were removed from Connect.  So if the Connect is upgraded to 6.0.0, we need to run confluent-hub to install the connectors.  Options to proceed:

1. This PR: downgrade just the Connect images to 5.5.1, create separate PR for tutorial modification to run 6.0.0 connectors & confluent-hub
2. This PR: do it all ;) 

preferences?

**Comment by rspurgeon** [comment]
> Options to proceed:
> 
>     1. This PR: downgrade just the Connect images to 5.5.1, create separate PR for tutorial modification to run 6.0.0 connectors & confluent-hub
> 
>     2. This PR: do it all ;)
> 
> 
> preferences?

I vote 1

**Comment by bbejeck** [comment]
>I know what the issue is: in 6.0.0, all connectors were removed from Connect (the JDBC connector is no longer pre-bundled). 

Ah, thanks for the explanation @ybyzek, I was thinking it was a packaging issue.

my vote is for option 1 as well

**Comment by ybyzek** [comment]
👍 @bbejeck @rspurgeon I filed https://github.com/confluentinc/kafka-tutorials/issues/580 to track the connect issue for upgrading to 6.0.0, and meanwhile this PR will download to 5.5.1

**Comment by ybyzek** [comment]
👍 @bbejeck @rspurgeon I filed #582 to track the updating the client code

**Comment by ybyzek** [comment]
@bbejeck with the latest set of changes, it looks like 2 tests are failing in the 2nd block of Semaphore tests.  I looked at the output and IIUC they are failing at the end, during shutdown.  Is it the case that these failures are part of a flakey test and we can still declare the PR a pass (and thus can be merged), or is there an outstanding issue I should resolve in this PR?

**Comment by bbejeck** [comment]
> I looked at the output and IIUC they are failing at the end, during shutdown? Is it the case that these failures are part of a flakey test and we can still declare the PR a pass (and thus can be merged), or is there an outstanding issue I should resolve in this PR

I'm not sure, it seems the `KStreams emit final result...` test has been consistently failing, IIRC from the previous builds.  I can help take a look if you want.

**Comment by ybyzek** [comment]
@bbejeck when I build the `window-final-result` tutorial locally, it appears to succeed locally but ultimately fails because the diff isn't exactly -- there are blank lines:

```
cat tutorial-steps/dev/expected-count.txt
5
1
1
2
```

versus

```
cat tutorial-steps/dev/outputs/actual-count.txt
5
1
1
2



```

So this check fails:

```
[16:10:12] ~/git/kafka-tutorials/_includes/tutorials/window-final-result/kstreams/code(GH-461) ✗: bash -c 'diff --strip-trailing-cr <(cat tutorial-steps/dev/expected-count.txt) <(cat tutorial-steps/dev/outputs/actual-count.txt)'

4a5,7
> 
> 
> 
[16:10:20] ~/git/kafka-tutorials/_includes/tutorials/window-final-result/kstreams/code(GH-461) ✗: echo $?
1

```

But this check passes (Notice the addition of the `-B` flag):

```
[16:10:22] ~/git/kafka-tutorials/_includes/tutorials/window-final-result/kstreams/code(GH-461) ✗: bash -c 'diff -B --strip-trailing-cr <(cat tutorial-steps/dev/expected-count.txt) <(cat tutorial-steps/dev/outputs/actual-count.txt)'                   

[16:10:35] ~/git/kafka-tutorials/_includes/tutorials/window-final-result/kstreams/code(GH-461) ✗: echo $?
0

```

I would appreciate your feedback:

1. Confirm that this PR is good to go (if you think it is) ... that you agree the Semaphore failures are unrelated to the PR changes
2. Confirm that the `-B` flag is useful and I can file a GH issue to add it to the Makefile.

**Comment by bbejeck** [comment]
@ybyzek 

The `-B` flag is a great find! Definitely add an issue to add this to the makefile.

Something I missed earlier - the `KStreams Test Streams schedule operations tests` seems to fail consistently.  Can't say for sure if it's related to this update or not.  If you want you can merge this and create an issue for the `schedule operations` failure, it's up to you.

**Comment by ybyzek** [comment]
Thanks @bbejeck .  I have filed a total of 4 new issues resulting from this PR 😄 

https://github.com/confluentinc/kafka-tutorials/issues/580
https://github.com/confluentinc/kafka-tutorials/issues/582
https://github.com/confluentinc/kafka-tutorials/issues/583
https://github.com/confluentinc/kafka-tutorials/issues/584

At this point, do approve this PR for merge @bbejeck ?

**Comment by bbejeck** [comment]
yep

**Pull request merged**
