### PR TITLE
DEVX-2009: Scheduling operations with streams punctuation

### PR DESCRIPTION
**Pull request by bbejeck**
covers https://github.com/confluentinc/kafka-tutorials/issues/357

### CODE REVIEW

**Comment by bbejeck** [comment]
relevant test passed https://confluentinc.semaphoreci.com/jobs/36e3e8bf-b2fc-4d99-afe1-ae97c3b408e6

ping @rspurgeon @ybyzek @gAmUssA  for review

**Comment by bbejeck** [comment]
ping @rspurgeon @gAmUssA @ybyzek  for review

**Comment by bbejeck** [comment]
rebased this PR

ping @rspurgeon @ybyzek @gAmUssA for review

**Comment by bbejeck** [comment]
ping @gAmUssA @rspurgeon @ybyzek for review

**Comment by bbejeck** [comment]
Test for this PR passed

**Review by gAmUssA — APPROVED** [review]
@bbejeck LGTM. I pushed a few tweaks (minor nit)

**Comment by bbejeck** [comment]
failing tests unrelated

**Comment by bbejeck** [comment]
Thanks for the review @gAmUssA

**Pull request merged**
