### PR TITLE
🧪 Updating jekyll and Jekyll-asciidoc to address some security issues

### PR DESCRIPTION
**Pull request by gAmUssA**

### CODE REVIEW

**Comment by gAmUssA** [comment]
@bbejeck whenever you have a chance, could you release the staging website so we can click it through to make sure that rendering is ok after the update

**Comment by bbejeck** [comment]
I pulled down this PR and verified by building locally

**Comment by gAmUssA** [comment]
@bbejeck can we merge then?

**Comment by bbejeck** [comment]
> @bbejeck can we merge then?

Probably,  but as an extra sanity check if we can get one or both of  @rspurgeon and @ybyzek to check out this PR and run `bundler install` and run the KT site locally with no issues, that would be ideal.

**Pull request merged**
