### PR TITLE
Move from Sbt to Gradle in produce/consume with scala

### PR DESCRIPTION
**Pull request by DivLoic**
As @gAmUssA requested, this is the Sbt/Gradle conversion for the first produce and consume tutorial. 

[asciicast](https://asciinema.org/a/358242)

Important notes: 
- Two submodules have been created for (produce and consume) to better stick to the jib Gradle plugin
- Dev executions and stdin input didn't work well with Gradle (DEV chapter uses java -jar commands)

### CODE REVIEW

**Comment by gAmUssA** [comment]
ACK @DivLoic 
Thank you for spending time refactoring it 
> Dev executions and stdin input didn't work well with Gradle (DEV chapter uses java -jar commands)

this one is no biggie at all - I prefer to run apps via `jar -jar` rather use build tools.
I will perform a full review later this week.
Cheers,
Vik

**Review by gAmUssA — CHANGES_REQUESTED** [review]
Thanks again for this PR

few notes

- kindly rebase upstream/master
- add gradle wrapper to your tutorial project
- make sure to run `./gradlew test` in kafka-tutorials root folder to make sure that this tutorial project compiles and will be executed with the rest of tutorials during CI for gradle projects

**Review by bbejeck — COMMENTED** [review]
Thanks for the update @DivLoic I don't have any comments modulo what @gAmUssA has pointed out.

Once those are addressed I think we can get this merged.

**Comment by DivLoic** [comment]
@gAmUssA @bbejeck , sorry for the delay! The wrapper has been added and the branch is updated!

**Comment by gAmUssA** [comment]
@DivLoic 

I'm doing a quick smoke test

```
❯ pwd
/Users/viktor/projects/confluent/kafka-tutorials

❯ ./gradlew test

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/viktor/projects/confluent/kafka-tutorials/_includes/tutorials/produce-consume-lang/scala/code/build.gradle' line: 80

* What went wrong:
A problem occurred evaluating project ':_includes:tutorials:produce-consume-lang:scala:code'.
> Project with path ':app-producer' could not be found in project ':_includes:tutorials:produce-consume-lang:scala:code'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 933ms
```

what am i doing wrong?

**Comment by gAmUssA** [comment]
my branch is up to date `16c3da`

**Comment by DivLoic** [comment]
Ok, so apparently I used to run the tests on tutorial only and not the root of Kafka-tutorials (what a selfish thing to do XD).

The tutorial it self has subprojects, so running the top level test reequires a little tweak. Please see and approve 1c4cae9.

Sorry about that!

**Comment by gAmUssA** [comment]
@DivLoic 

```
> Task :_includes:tutorials:produce-consume-lang:scala:code:compileTestScala
[Error] /Users/viktor/projects/confluent/kafka-tutorials/_includes/tutorials/produce-consume-lang/scala/code/src/test/scala/io/confluent/developer/KafkaFlatSpec.scala:3: object Configuration is not a member of package io.confluent.developer
[Error] /Users/viktor/projects/confluent/kafka-tutorials/_includes/tutorials/produce-consume-lang/scala/code/src/test/scala/io/confluent/developer/KafkaFlatSpec.scala:21: not found: type TopicSpec
two errors found
```

**Comment by DivLoic** [comment]
Hi @gAmUssA, I will look into it but it doesn't seem to append on my side

```
code ldivad-produce-consume-scala ✗ 12d △ 🍹 ➜ ./gradlew clean compileTestScala

> Task :produce-consume-scala-consumer-app:compileTestScala
[Warn] /Users/loicmdivad/workspace/opensource/kafka-tutorials/.../ConsumerSpec.scala:74: multiarg infix syntax looks like a tuple and will be deprecated
one warning found

> Task :produce-consume-scala-producer-app:compileTestScala
[Warn] /Users/loicmdivad/workspace/opensource/kafka-tutorials/.../ProducerSpec.scala:67: multiarg infix syntax looks like a tuple and will be deprecated
one warning found

BUILD SUCCESSFUL in 43s
12 actionable tasks: 12 executed
```

- Have you tried to add a `clean` to your test?
- Any details you could share with me about your Java/Gradle?

**Comment by gAmUssA** [comment]
@DivLoic correct. if you run `./gradlew build` from the root it will use config for the compiler that treats WARNING as compiler errors. specifically, it was activated to avoid usage of deprecated APIs.I hope it makes sense

**Comment by DivLoic** [comment]
@gAmUssA not really, `./gradlew build` from the root gives me a good result. And I think your previous message is yet a problem to solve. But I can get ride of the warnings easily!!!

**Comment by gAmUssA** [comment]
@DivLoic Thank you!

**Comment by gAmUssA** [comment]
@bbejeck do you know why I don't see this PR on semaphore?

**Comment by bbejeck** [comment]
>do you know why I don't see this PR on semaphore?

@gAmUssA there's no entry in the `semaphore.yml` file for it.

@DivLoic, can you add this to the  `.semaphore/semaphore.yml` file under one of the `jobs:` entry?

```yml
- name: Kafka produce and consume in Scala
          commands:
            - make -C _includes/tutorials/produce-consume-lang/scala/code tutorial
```

**Comment by DivLoic** [comment]
Thanks @bbejeck 🙏, I forgot about that one! @gAmUssA, the warnings have been resolved.

**Comment by gAmUssA** [comment]
@DivLoic you're ⭐️

**Pull request merged**
