### PR TITLE
DEVX-1781: [KAFKA 101 series] Console consumer w/ deserializers 

### PR DESCRIPTION
**Pull request by bbejeck**
Covers #341 but this should only get merged after #339 is merged

### CODE REVIEW

**Comment by bbejeck** [comment]
Updated to use the container shell when running `console consumer`

ping @rspurgeon @gAmUssA @ybyzek @tlberglund for a review

**Comment by bbejeck** [comment]
[The test](https://confluentinc.semaphoreci.com/jobs/95cee07a-685e-42de-a498-1c5bd8639cb3) for this PR passed.

**Comment by bbejeck** [comment]
updated and rebased this PR

ping one of @gAmUssA @colinhicks @rspurgeon for a review

**Comment by gAmUssA** [comment]
@bbejeck I took the liberty to fix few typos and formatting/rendering issues.

**Comment by bbejeck** [comment]
@gAmUssA thanks for the review!

**Pull request merged**
