### PR TITLE
GH-538: Add support for "Short answer" 

### PR DESCRIPTION
**Pull request by ybyzek**
Addresses https://github.com/confluentinc/kafka-tutorials/issues/538

Screen Shot 2020-10-12 at 08 26 55 AM

### CODE REVIEW

**Comment by ybyzek** [comment]
Latest staging: http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/GH-538/426e1352ce653272b2d5e1420aeafad25bf41bea/create-stateful-aggregation-count/ksql.html

**Comment by ybyzek** [comment]
Latest commit uses the background suggested by Ashlee.

Screen Shot 2020-10-09 at 11 58 48 AM

Staging: http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/GH-538/97851317c3283dd60c6c7c895a17f6f0c2ff3aae/create-stateful-aggregation-count/ksql.html

Based on meeting today, all were in favor.  @bbejeck would you want to provide final approval?

**Comment by gAmUssA** [comment]
can we just keep `TL;DR` without `(Short answer)`? it's just awkward. I understand SEO side of things. but still

**Comment by rmoff** [comment]
+1 to what @gAmUssA said. `tl;dr (short answer)` looks clumsy. By adopting `tl;dr` we're going after the developer colloquial terminology, and then ruin it with the parentheses. 
If we're worried about the comprehension of the term we could always link to an explanation of it with a little asterisk or something like that, or a hover-over tool tip, or something.

**Comment by ybyzek** [comment]
- Latest commit changes `tl;dr` to `TL;DR`.
- Reasons to keep `(Short answer)` are comprehension of term & SEO (as discussed on the call).  I lean towards keeping it because not everyone knows what it means, and it shouldn't take a link out to explain it.

**Comment by gAmUssA** [comment]
can we rather wrap a link to https://en.wikipedia.org/wiki/TL%3BDR for `TLDR` and remove short answer?

**Comment by gAmUssA** [comment]
we always can opt in for «Executive Summary»

**Comment by bbejeck** [comment]
>Reasons to keep (Short answer) are comprehension of term & SEO (as discussed on the call). I lean towards keeping it because not everyone knows what it means, and it shouldn't take a link out to explain it.

I've been thinking about this, and I'm inclined to agree with @ybyzek. IMHO the value of presenting the concise answer upfront offsets the additional words.

**Comment by rmoff** [comment]
I'm a hard no on including `quick answer`, and feel strongly we go for just `tl;dr`. 

With both,  we are like dad trying to be cool dancing at the disco, but actually just embarrassing himself. Speaking purely for my own dancing skills here 🕺 

> Reasons to keep (Short answer) are comprehension of term & SEO (as discussed on the call). I lean towards keeping it because not everyone knows what it means, and it shouldn't take a link out to explain it.

Comprehension: we can hyperlink, we can do tooltips; there are plenty of webdev techniques to facilitate explanation if we need it

SEO: I think this is not a sacrifice worth making for SEO. SEO is only part of the requirement; making things that are appealing to developers and speaks to them in their own voice without seeming clunk is another.

**Comment by ybyzek** [comment]
@rmoff if doing both (i.e., `TL;DR (Short Answer)`) is the uncool dad, then let's just make it `Short Answer`.  The concern with having just `TL;DR` is that it leaves folks out of the loop, and we want to be as inclusive as possible so that these tutorials can be accessible and useful for everyone.  `Short Answer` is unambiguous.

**Comment by ybyzek** [comment]
Discussed offline with @rmoff and @gAmUssA -- we agreed to move forward with `Short Answer`

**Review by bbejeck — APPROVED** [review]
LGTM

**Pull request merged**
