### PR TITLE
KT release [August 6, 2021]

### PR DESCRIPTION
**Pull request by ybyzek**
### Description

This release includes the following PRs:

- https://github.com/confluentinc/kafka-tutorials/pull/913
- https://github.com/confluentinc/kafka-tutorials/pull/910
- https://github.com/confluentinc/kafka-tutorials/pull/907
- https://github.com/confluentinc/kafka-tutorials/pull/912

### Staging Docs

Deployed to http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master/

### CODE REVIEW

**Review by rspurgeon — APPROVED** [review]
LGTM

**Comment by ybyzek** [comment]
@danshafie can you please look at this staging?  It incorporates your PR https://github.com/confluentinc/kafka-tutorials/pull/913.  The issue is that the links appear to render on the landing page (scroll to bottom of http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master/), but not on each individual tutorial page (scroll to bottom of http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master/connect-add-key-to-source/kstreams.html). 

Screen Shot 2021-08-06 at 10 10 58 AM

**Comment by danshafie** [comment]
> @danshafie can you please look at this staging? It incorporates your PR #913. The issue is that the links appear to render on the landing page (scroll to bottom of http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master/), but not on each individual tutorial page (scroll to bottom of http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master/connect-add-key-to-source/kstreams.html).
> 
> Screen Shot 2021-08-06 at 10 10 58 AM

hey @ybyzek sorry about that, i missed that the tutorial html page needed the font awesome script as well. I raised a PR here to fix - [https://github.com/confluentinc/kafka-tutorials/pull/915](url). let me know if you need anything else

**Comment by ybyzek** [comment]
@danshafie thanks for the quick turnaround.  LGTM!

**Comment by ybyzek** [comment]
Test failures not from this PR.  Merging

**Pull request merged**
