### PR TITLE
Live site release - 10 April 2020

### PR DESCRIPTION
**Pull request by bbejeck**
New tutorials:

- (KSQL) Handling deserialization errors 
- (KStreams) Running average
- (KStreams) Naming stateful operators
- (KStreams) Choosing output topics at runtime
- (KSQL) Connect add key to source
- (Kafka) Connect add key to source

This release also updates all existing KSQL tutorials to the 0.8.1 version of ksqlDB.

The release includes some minor enhancements and bug fixes as well.

Thanks to all who contributed!

### CODE REVIEW

**Comment by bbejeck** [comment]
staged at http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master/af692899ba124cb96f6d8113e9351765735092a7/

**Comment by colinhicks** [comment]
I messed up the styles for the new header on smaller screen sizes :/. Will need to push a fix.
image

**Comment by bbejeck** [comment]
I included some images in the  /assets/tutorial_images/naming-changelog-repartition-topics directory.  They show up on local deployment, but they don't show on the staging site ( 404 looking at chrome tools) so I need to make some quick changes as well
Screen Shot 2020-04-10 at 5 58 50 PM

**Comment by bbejeck** [comment]
updated preview deployed

http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master/671423280cb29498d256384671c9eea80e04a0e6/

**Comment by bbejeck** [comment]
the update for #322 checks out

**Comment by colinhicks** [comment]
#323 looks good, too

**Comment by bbejeck** [comment]
Thanks for the review promoted `release` to the live website at [b3c8994](#321)

**Pull request merged**
