### PR TITLE
Unique icons for cards

### PR DESCRIPTION
**Pull request by ybyzek**
### Description

This PR adds unique icons for the new cards that @bbejeck is adding in the parent PR

@colinhicks -- I tried to download SVG and resize but was unable to do so.  I used PNG instead but sharp eyes might detect that it's grainier.  Thoughts on whether these images are ok as-is or if changes are required?  (If changes are required, I'd appreciate your guidance on how to get SVG resized)

### Staging Docs

http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/YB-new-icons/

### CODE REVIEW

**Review by bbejeck — APPROVED** [review]
LGTM!

**Comment by bbejeck** [comment]
Thanks for doing this @ybyzek!

**Comment by colinhicks** [comment]
@ybyzek it does appear that the PNGs are lower resolution than ideal for high-PPI (retina) screens. 

To match the apparent size of the existing SVGs, my guess is the new SVGs need width and height attributes:
`<svg width="40" height="40" ...>` in the root node. This tweak can be done by editing the SVG in a text editor.

**Comment by ybyzek** [comment]
@colinhicks cool, I wasn't aware you could text edit SVG files in that manner.  @bbejeck may I add another PR to https://github.com/confluentinc/kafka-tutorials/tree/MINOR_update_index_page_layout to address this?

**Comment by bbejeck** [comment]
>  I add another PR to https://github.com/confluentinc/kafka-tutorials/tree/MINOR_update_index_page_layout to address this?

@ybyzek sure thing, but let me push some changes first

**Pull request merged**
