### PR TITLE
Rename Confluent Cloud UI to Confluent Cloud Console

### PR DESCRIPTION
**Pull request by ybyzek**
### Staging Docs

http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/cloud-console

### CODE REVIEW

**Review by rspurgeon — APPROVED** [review]
LGTM

**Review by bbejeck — APPROVED** [review]
LGTM

**Comment by bbejeck** [comment]
@ybyzek a unit test failed https://confluentinc.semaphoreci.com/jobs/209ea1f4-089c-4820-91f2-9eddffb2557b which is strange because this PR didn't modify any java code.  I kicked off a new build

**Review by vsyu — APPROVED** [review]
LGTM

**Pull request merged**
