### PR TITLE
KT release [04/20/2021]

### PR DESCRIPTION
**Pull request by ybyzek**
### Description

New tutorials:

- 6 new Confluent Cloud KTs (#796)
- Merge pull request #761 from confluentinc/ktable-ttl
- Merge pull request #741 from confluentinc/DEVX-2487_add_streams_error…

Other

- GH-708: #708 Make card headings consistent wrt verb tense (#709)
- GH-580: #580: update versions for Confluent, Apache Kafka, Gradle (#752)
- Remove deprecated flag --broker-list in favour of --bootstrap-server
- Various minor fixes

### Before merge

- [x] Reminder to `Merge` (do not `Squash/Merge`)

### Note

This PR pulls in older commits that precede the last KT release done on March 5, 2021 (https://github.com/confluentinc/kafka-tutorials/pull/748), that are already part of the `release` branch.  Normally these shouldn't show up in this PR, but the hypothesis is that the March 5 KT release PR was Squashed/Merged instead of just Merged, so all the child commits weren't part of `release` Git history, so it looks like "new" commits.  They are not new, they are already there.

### Staging Docs

http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master/

### CODE REVIEW

**Review by rspurgeon — APPROVED** [review]
LGTM, verified by manually validating the staged KT site

**Comment by ybyzek** [comment]
@gAmUssA 🙌 🥇 awesome!  Thank you for this fix!

The fix is references Gradle version 6.8.3

```
sudo apt-get install gradle-6.8.3 -y
```

However, the code uses 6.7.1 throughout:

```
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-bin.zip
```

Should this be consistent?

**Comment by ybyzek** [comment]
Rerunning test build on this PR @bbejeck, all.

**Review by bbejeck — APPROVED** [review]
LGTM

Validated on Chrome and FF desktop and Mobile (iPhone 10)  Chrome and Safari

**Comment by gAmUssA** [comment]
all green, yay!

**Comment by gAmUssA** [comment]
> @gAmUssA 🙌 🥇 awesome! Thank you for this fix!
> 
> The commit references Gradle version 6.8.3
> 
> ```
> sudo apt-get install gradle-6.8.3 -y
> ```
> 
> However, the tutorials use version 6.7.1 throughout:
> 
> ```
> distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-bin.zip
> ```
> 
> Should this be consistent?

I couldn't find 6.7x version in apt repository that semaphore uses 🤷  https://launchpad.net/~cwchien/+archive/ubuntu/gradle

Ideally, we should definitely be consistent with versions but 6.x (eg 6.7 and 6.8) API should be compatible.

**Review by gAmUssA — APPROVED** [review]

**Comment by bbejeck** [comment]
All green build!

**Pull request merged**
