### PR TITLE
Kafka Tutorials Release [06-26-2020]

### PR DESCRIPTION
**Pull request by bbejeck**
This release will contain 

- Videos from @gAmUssA for tutorials
- Improved documentation for harness-runner
- Updated serialization tutorials
- improved support for asciidoc in tutorial markup

### CODE REVIEW

**Comment by bbejeck** [comment]
staged at http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master/8ecc39c5b8a5480b82debeeec57e252b40f8f045/

**Comment by bbejeck** [comment]
ping @ybyzek @rspurgeon @gAmUssA @tlberglund for a review

**Comment by bbejeck** [comment]
LGTM

Validated KT on Chrome, Firefox, Safari, and Chrome on IPhone including:
videos display correctly form Transforming tutorial
new asciidoc support in Serialization tutorial

**Comment by gAmUssA** [comment]
@bbejeck I'm on it

**Comment by bbejeck** [comment]
pushed live to release via https://github.com/confluentinc/kafka-tutorials/commit/9a7f0df35a84f5c3e7d477e853d330e86385f04e

**Pull request merged**
