### PR TITLE
Tooltip and Asciidoc

### PR DESCRIPTION
**Pull request by hartantothio**
# Description

Addressing some issues and new feature request:
- https://github.com/confluentinc/kafka-tutorials/issues/381
- https://github.com/confluentinc/kafka-tutorials/issues/87
- https://github.com/confluentinc/kafka-tutorials/issues/98

# Screenshots
Asciidoc
ec2-13-56-160-111 us-west-1 compute amazonaws com_ceo-friendly-link-to-my-tutorial_ksql html

Tooltip (after clicked)
image

### CODE REVIEW

**Comment by gAmUssA** [comment]
live preview http://ec2-13-56-160-111.us-west-1.compute.amazonaws.com/ceo-friendly-link-to-my-tutorial/ksql.html

**Comment by bbejeck** [comment]
Verified by running the site locally and checking existing tutorials.

**Comment by bbejeck** [comment]
Thanks @hartantothio! These changes will make a big difference.

**Comment by hartantothio** [comment]
👍

**Pull request merged**
