### PR TITLE
KT release [12/17/2020]

### PR DESCRIPTION
**Pull request by awalther28**
### Description

New KTs: [column concatenation](https://github.com/confluentinc/kafka-tutorials/pull/660), [column difference](https://github.com/confluentinc/kafka-tutorials/pull/671), and [multiway joins](https://github.com/confluentinc/kafka-tutorials/pull/665)

### CODE REVIEW

**Review by rspurgeon — APPROVED** [review]
LGTM

**Review by ybyzek — APPROVED** [review]
LGTM validated on Safari

**Comment by awalther28** [comment]
Note: the test that failed is "KStreams Connect Key tests". This test has passed in the past 2 days on the master branch and  no content related to that tutorial or test appears to have changed since its last time passing.

**Review by bbejeck — APPROVED** [review]
LGTM

Validated on Firefox and Chrome desktop and Chrome on iPhone 10

**Pull request merged**
