### PR TITLE
KAFKA TUTORIALS [Release 10-29-2020]

### PR DESCRIPTION
**Pull request by bbejeck**
This release will have 3 new tutorials

1. Maintain message order with the idempotent producer - @ybyzek 
2. Data masking - @awalther28 
3. Detecting abnormal transactions - @awalther28  

Plus some minor fixes (dependency updates) and auto-deployment to staging for PRs

### CODE REVIEW

**Comment by bbejeck** [comment]
All the tests passed! WOOT!

staged at http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master/

**Comment by ybyzek** [comment]
@bbejeck the default view when bringing up KT shows a long list in Kafka 101 and a collapsed list in Apply Function.  It looks a bit unbalanced, so WDYT about either (a) adding the more/less button to Kafka 101, or (b) removing the more/less button from Apply Function?

Screen Shot 2020-10-29 at 19 07 55 PM

**Review by ybyzek — APPROVED** [review]
@bbejeck one comment for consideration about the card more/less button -- I defer to you.  Otherwise LGTM.  And @awalther28 way to go with killer tutorials!

**Review by awalther28 — APPROVED** [review]
I feel good about promoting this. Cool tutorial @ybyzek 👍

**Review by gAmUssA — APPROVED** [review]
Awesome two new tutorials!

**Comment by bbejeck** [comment]
release covered by  https://github.com/confluentinc/kafka-tutorials/commit/9ab1e772c1e0a25898f13751dd8bd694316f9fa4

**Pull request merged**
